# Generated by Django 6.0.6 on 2026-06-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_spaces',
            field=models.IntegerField(blank=True, help_text='Leave blank for unlimited spaces', null=True),
        ),
        migrations.CreateModel(
            name='SeniorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='payments.site')),
            ],
        ),
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='payments.activity')),
            ],
            options={
                'unique_together': {('activity', 'session_key')},
            },
        ),
    ]
