# Generated by Django 6.0.6 on 2026-06-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_activity_max_spaces_seniorinvite_bookinghold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price_pennies',
            field=models.IntegerField(help_text='Price stored in pence (e.g. £10.50 = 1050)'),
        ),
        migrations.DeleteModel(
            name='SeniorInvite',
        ),
    ]
