# Generated by Django 6.0.6 on 2026-06-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_activity_price_pennies_delete_seniorinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='payment_closes_at',
            field=models.DateField(blank=True, help_text='Optional closing date – payments will not be accepted on or after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make this activity available across all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='payments.site'),
        ),
    ]
