# Generated by Django 6.0.6 on 2026-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_activity_payment_closes_at_alter_activity_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_test',
            field=models.BooleanField(default=True, help_text='Whether this payment was made in Stripe test mode'),
        ),
    ]
