# Generated by Django 6.0.6 on 2026-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_appsetting_payment_paid_by_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='value',
            field=models.CharField(default='False', max_length=500),
        ),
    ]
