# Generated by Django 6.0.6 on 2026-06-25 19:31

from django.db import migrations


def migrate_balance_setting(apps, schema_editor):
    AppSetting = apps.get_model("payments", "AppSetting")
    old = AppSetting.objects.filter(key="balance_feature_enabled").first()
    if old and old.value and old.value.lower() == "true":
        AppSetting.objects.update_or_create(
            key="wallet_system_enabled",
            defaults={"value": "True"},
        )
    if old:
        old.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_appsetting_value'),
    ]

    operations = [
        migrations.RunPython(migrate_balance_setting, migrations.RunPython.noop),
    ]
